x-db-default: &db-default
  image: postgres:14-alpine
  restart: always
  read_only: true
  tmpfs:
    - /tmp
    - /var/run/postgresql

services:
  nexus:
    image: nexus:latest
    build:
      context: .
      target: nexus
    restart: always
    read_only: true
    environment:
      LIBEUFIN_NEXUS_DB_CONNECTION: "jdbc:postgresql://db-nexus:5432/eufin_nexus?user=eufin_nexus&password=eufin_nexus"
    ports:
      - "5001:5001"
    networks:
      db-nexus: {}
      default: {}
    depends_on:
      - db-nexus

  db-nexus:
    <<: *db-default
    volumes:
      - db-nexus_data:/var/lib/postgresql/data
    networks:
      db-nexus: {}
    environment:
      POSTGRES_USER: eufin_nexus
      POSTGRES_PASSWORD: eufin_nexus

  sandbox: &sandbox
    image: sandbox:latest
    build:
      context: .
      target: sandbox
    restart: always
    read_only: true
    environment:
      LIBEUFIN_SANDBOX_DB_CONNECTION: "jdbc:postgresql://db-sandbox:5432/eufin_sandbox?user=eufin_sandbox&password=eufin_sandbox"
      LIBEUFIN_SANDBOX_ADMIN_PASSWORD: hunter2
    ports:
      - "5002:5002"
    networks:
      db-sandbox: {}
      default: {}
    depends_on:
      - db-sandbox

  db-sandbox:
    <<: *db-default
    volumes:
      - db-sandbox_data:/var/lib/postgresql/data
    networks:
      db-sandbox: {}
    environment:
      POSTGRES_USER: eufin_sandbox
      POSTGRES_PASSWORD: eufin_sandbox

networks:
  db-nexus:
    internal: true
    driver: bridge
  db-sandbox:
    internal: true
    driver: bridge
  default:

volumes:
  db-nexus_data:
  db-sandbox_data:
