name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          # Strip git ref prefix from version
          IMAGE_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && IMAGE_VERSION=$(echo $IMAGE_VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$IMAGE_VERSION" == "main" ] && IMAGE_VERSION=latest
          export IMAGE_VERSION
          docker compose build
          docker compose push
